"""Initial_migration1

Revision ID: 177a3cd723ad
Revises: ee5dd431e037
Create Date: 2021-05-28 14:29:37.716201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '177a3cd723ad'
down_revision = 'ee5dd431e037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('work_address', sa.Integer(), nullable=True),
    sa.Column('key_skill', sa.Integer(), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['Department.id'], ),
    sa.ForeignKeyConstraint(['key_skill'], ['Skills.id'], ),
    sa.ForeignKeyConstraint(['location'], ['Locations.id'], ),
    sa.ForeignKeyConstraint(['permission'], ['Permissions.id'], ),
    sa.ForeignKeyConstraint(['work_address'], ['Addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('salary', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_of_joining', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('work_address', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key_skill', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department'], ['Department.id'], name='employees_department_fkey'),
    sa.ForeignKeyConstraint(['key_skill'], ['Skills.id'], name='employees_key_skill_fkey'),
    sa.ForeignKeyConstraint(['location'], ['Locations.id'], name='employees_location_fkey'),
    sa.ForeignKeyConstraint(['permission'], ['Permissions.id'], name='employees_permission_fkey'),
    sa.ForeignKeyConstraint(['work_address'], ['Addresses.id'], name='employees_work_address_fkey'),
    sa.PrimaryKeyConstraint('id', name='employees_pkey')
    )
    op.drop_table('Employees')
    # ### end Alembic commands ###
