"""Initial_migration

Revision ID: ee5dd431e037
Revises: 
Create Date: 2021-05-28 14:28:40.871725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee5dd431e037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('work_address', sa.Integer(), nullable=True),
    sa.Column('key_skill', sa.Integer(), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['Department.id'], ),
    sa.ForeignKeyConstraint(['key_skill'], ['Skills.id'], ),
    sa.ForeignKeyConstraint(['location'], ['Locations.id'], ),
    sa.ForeignKeyConstraint(['permission'], ['Permissions.id'], ),
    sa.ForeignKeyConstraint(['work_address'], ['Addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employees',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Employees_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('salary', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_of_joining', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('work_address', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key_skill', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department'], ['Department.id'], name='Employees_department_fkey'),
    sa.ForeignKeyConstraint(['key_skill'], ['Skills.id'], name='Employees_key_skill_fkey'),
    sa.ForeignKeyConstraint(['location'], ['Locations.id'], name='Employees_location_fkey'),
    sa.ForeignKeyConstraint(['permission'], ['Permissions.id'], name='Employees_permission_fkey'),
    sa.ForeignKeyConstraint(['work_address'], ['Addresses.id'], name='Employees_work_address_fkey'),
    sa.PrimaryKeyConstraint('id', name='Employees_pkey')
    )
    op.drop_table('employees')
    # ### end Alembic commands ###
